name: build_and_download

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y doxygen liblua5.4-dev libglib2.0-dev
          pip install sphinx-rtd-theme Sphinx myst-parser

      - name: Build Docs
        run: |
          cmake -B ${{github.workspace}}/build
          cd build
          make doc

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: ${{github.workspace}}/build/docs/_build
          retention-days: 7
